// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk8Czk_IxOLIMNtqaEkysBPoXhRihLYS0',
    appId: '1:22726237797:web:1ea79c50d62ec4876cb08c',
    messagingSenderId: '22726237797',
    projectId: 'education-center-dac',
    authDomain: 'education-center-dac.firebaseapp.com',
    storageBucket: 'education-center-dac.appspot.com',
    measurementId: 'G-F8NXX2XJ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB9MCHEBpP6t22Y-i6eOkFA_Lco7rYLrE',
    appId: '1:22726237797:android:823da1f17e1feb8a6cb08c',
    messagingSenderId: '22726237797',
    projectId: 'education-center-dac',
    storageBucket: 'education-center-dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRdfUGMPInfRwpG7Up9loGEiWCIIL8bA',
    appId: '1:22726237797:ios:1974fc494d61664f6cb08c',
    messagingSenderId: '22726237797',
    projectId: 'education-center-dac',
    storageBucket: 'education-center-dac.appspot.com',
    iosClientId: '22726237797-8avue7a2t0jekbu01mfrq1qu4dqfo376.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRdfUGMPInfRwpG7Up9loGEiWCIIL8bA',
    appId: '1:22726237797:ios:85989baba9b7154d6cb08c',
    messagingSenderId: '22726237797',
    projectId: 'education-center-dac',
    storageBucket: 'education-center-dac.appspot.com',
    iosClientId: '22726237797-u76ldv8cd61mm2hhvvhuqe9l5pgnhqch.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTc.RunnerTests',
  );
}
