// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYhC8jPDv9g08k1GwQcHcC1clnlXwCNk',
    appId: '1:42079161450:web:55ae4af228886ad2e4ce13',
    messagingSenderId: '42079161450',
    projectId: 'project-tc-00',
    authDomain: 'project-tc-00.firebaseapp.com',
    storageBucket: 'project-tc-00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHBQB1XZPWbvVNzbQyJbEENirE-yNp0Z4',
    appId: '1:42079161450:android:aa9ab73babfc3cdbe4ce13',
    messagingSenderId: '42079161450',
    projectId: 'project-tc-00',
    storageBucket: 'project-tc-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5E9kVaUpzyu2Bc7kFtQKLtlH7Y_Lr4c',
    appId: '1:42079161450:ios:4d5749146bdd65cfe4ce13',
    messagingSenderId: '42079161450',
    projectId: 'project-tc-00',
    storageBucket: 'project-tc-00.appspot.com',
    iosClientId: '42079161450-gq7h8nj0unpn7qvsloe0f8mse07pmdkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5E9kVaUpzyu2Bc7kFtQKLtlH7Y_Lr4c',
    appId: '1:42079161450:ios:a8ca669663027eefe4ce13',
    messagingSenderId: '42079161450',
    projectId: 'project-tc-00',
    storageBucket: 'project-tc-00.appspot.com',
    iosClientId: '42079161450-20er5d8fodmdd60qdr1pj5g5gqg0bcds.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTc.RunnerTests',
  );
}
